//! # audit_log.rs – Structured JSON Security Event Logger
//!
//! Every block or challenge decision is emitted as a single-line JSON object
//! via `log::warn!` (challenges) or `log::error!` (blocks). Envoy captures
//! these lines in its error log stream, which SIEM agents (Elastic Filebeat,
//! Splunk UF) tail and ingest.
//!
//! ## Log injection hardening
//! All user-controlled strings (path, IP, evidence) are passed through
//! `types::sanitise_evidence` before serialisation. The JSON is produced
//! by serde_json, which escapes special characters, providing a second
//! layer of protection.
//!
//! ## SIEM field mapping
//! Field names are chosen to align with Elastic Common Schema (ECS) where
//! possible so SIEM teams can build dashboards without custom field mappings.

use crate::types::{Decision, ThreatReport};
use serde::Serialize;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

// ─────────────────────────────────────────────────────────────────────────────
// Audit event schema
// ─────────────────────────────────────────────────────────────────────────────

/// Serialisable audit event. One instance is emitted per blocked/challenged
/// request, containing all the evidence needed for an incident investigation.
#[derive(Serialize)]
struct AuditEvent<'a> {
    /// Unix epoch milliseconds – stable across time zones.
    timestamp: u64,

    tenant_id: &'a str,

    /// Unique ID for tracing the request through the system.
    correlation_id: String,

    /// ECS: `source.ip` – leftmost value from x-forwarded-for.
    source_ip: &'a str,

    /// ECS: `http.request.method`
    method: &'a str,

    /// ECS: `url.path` – truncated to 512 chars to prevent log flooding.
    uri: &'a str,

    /// Canonical attack category string from [`crate::types::AttackType`].
    attack_type: &'a str,

    /// Confidence score that triggered the decision (0.0–1.0).
    confidence: f32,

    /// Zero-based rule index for cross-referencing the OWASP rule catalogue.
    #[serde(skip_serializing_if = "Option::is_none")]
    rule_id: Option<usize>,

    /// Final WAF action taken (BLOCK / CHALLENGE / ALLOW).
    action: &'a str,

    /// The client's User-Agent string.
    user_agent: &'a str,

    /// Computed or provided GeoIP country code (stubbed for now).
    country_code: &'a str,

    /// Score generated by the ML/AI sidecar analysis
    ai_score: f32,
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/// Emit a structured audit log entry for a security event.
///
/// ## Parameters
/// * `report`   – The primary threat finding that drove the decision.
/// * `method`   – HTTP verb (GET, POST, …).
/// * `path`     – Request path (may contain query string).
/// * `ip`       – Originating client IP address.
/// * `ai_score` – Risk score from the semantic analysis stage.
/// * `decision` – Final enforcement decision taken.
///
/// ## Behaviour
/// * [`Decision::Block`]     → logged at `error` level.
/// * [`Decision::Challenge`] → logged at `warn` level.
/// * [`Decision::Allow`]     → no audit entry (debug logging only).
pub fn log_event(
    report: &ThreatReport,
    method: &str,
    path: &str,
    ip: &str,
    user_agent: &str,
    ai_score: f32,
    decision: &Decision,
    tenant_id: &str,
) {
    // Generate a simple correlation ID based on timestamp and an address counter or random.
    // In a real proxy-wasm setting, this could come from x-request-id if available.
    let corr_id = format!("req-{:x}-{}", now_ms(), report.confidence.to_bits());

    let event = AuditEvent {
        timestamp: now_ms(),
        tenant_id: tenant_id,
        correlation_id: corr_id,
        source_ip: ip,
        method: method,
        // Truncate path to 512 chars
        uri: &path[..path.len().min(512)],
        attack_type: report.attack_type.as_str(),
        confidence: report.confidence,
        rule_id: report.rule_id,
        action: decision_str(decision),
        user_agent: user_agent,
        country_code: "UNKNOWN",
        ai_score: ai_score,
    };

    match serde_json::to_string(&event) {
        Ok(json) => match decision {
            Decision::Block => log::error!(target: "neuroguard_waf", "{}", json),
            Decision::Challenge => log::warn! (target: "neuroguard_waf", "{}", json),
            Decision::Allow => log::debug!(target: "neuroguard_waf", "{}", json),
        },
        Err(e) => {
            // Serialisation failure should never happen with this fixed schema
            // but we degrade to a plain-text fallback rather than silently
            // dropping the event, which would be a security audit gap.
            log::error!(
                target: "neuroguard_waf",
                "{{\"error\":\"audit_serialise_failed\",\"detail\":\"{}\"}}",
                e
            );
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

fn decision_str(d: &Decision) -> &'static str {
    match d {
        Decision::Block => "BLOCK",
        Decision::Challenge => "CHALLENGE",
        Decision::Allow => "ALLOW",
    }
}

/// Current Unix time in milliseconds.
/// `SystemTime` is shimmed by the Wasm runtime; it reads the host clock
/// via the WASI `clock_time_get` import automatically.
fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or(Duration::ZERO) // UNIX_EPOCH is the fallback – never panics
        .as_millis() as u64
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::AttackType;

    fn make_report() -> ThreatReport {
        ThreatReport::new(AttackType::SqlInjection, 0.97, "UNION SELECT", Some(0))
    }

    #[test]
    fn log_event_does_not_panic_on_block() {
        log_event(
            &make_report(),
            "POST",
            "/api/login",
            "10.0.0.1",
            "curl/8.0",
            0.0,
            &Decision::Block,
            "00000000-0000-0000-0000-000000000000",
        );
    }

    #[test]
    fn log_event_does_not_panic_on_challenge() {
        log_event(
            &make_report(),
            "GET",
            "/search",
            "192.168.1.1",
            "Mozilla/5.0",
            0.5,
            &Decision::Challenge,
            "00000000-0000-0000-0000-000000000000",
        );
    }

    #[test]
    fn audit_event_serialises_to_valid_json() {
        let report = make_report();
        let event = AuditEvent {
            timestamp: 1_700_000_000_000,
            tenant_id: "00000000-0000-0000-0000-000000000000",
            correlation_id: "req-123".to_string(),
            source_ip: "1.2.3.4",
            method: "POST",
            uri: "/login",
            attack_type: report.attack_type.as_str(),
            confidence: report.confidence,
            rule_id: report.rule_id,
            action: "BLOCK",
            user_agent: "Mozilla/5.0",
            country_code: "UNKNOWN",
            ai_score: 0.97,
        };
        let json = serde_json::to_string(&event).expect("serialise failed");
        assert!(json.contains("\"attack_type\":\"SQL_INJECTION\""));
        assert!(json.contains("\"action\":\"BLOCK\""));
        assert!(json.contains("\"rule_id\":0"));
    }

    #[test]
    fn path_truncation_in_log_event() {
        // A 600-byte path must not cause a panic or produce a 600-byte path field.
        let long_path = "A".repeat(600);
        log_event(
            &make_report(),
            "GET",
            &long_path,
            "1.2.3.4",
            "Mozilla/5.0",
            0.0,
            &Decision::Block,
            "00000000-0000-0000-0000-000000000000",
        );
        // No assertion needed beyond "does not panic"; the truncation logic
        // is tested here by exercising the slice operation.
    }
}
